/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql.gui;

/**
 *
 * @author Jur Yel
 */
import mysql.core.Payment;
import mysql.dao.PaymentDAO;
import mysql.core.Booking;
import mysql.dao.BookingDAO;
import java.util.ArrayList;
import mysql.core.Hotel;
import mysql.dao.HotelDAO;
import java.util.Date;
import javax.swing.JOptionPane;

public class HomeUI_Payment extends javax.swing.JDialog {

    /**
     * Creates new form HomeUI_Payment
     */
    private PaymentDAO payDAO;
    private Booking booking;
    private BookingDAO bookDAO;
    private HotelDAO hotelDAO;
    private HomePageUI homeUI;
    private double payment;
    
    public HomeUI_Payment(Booking book,BookingDAO dao,double pay,HomePageUI ui){
        try{
            payDAO = new PaymentDAO();
            hotelDAO = new HotelDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(ui);
        bookDAO = dao;
        booking = book;
        payment = pay;
        populateGUI();
    }
    
    public HomeUI_Payment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbl_Name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbl_RoomType = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbl_BookDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlbl_CheckIn = new javax.swing.JLabel();
        jlbl_CheckOut = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlbl_Nights = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlbl_Payment = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxt_Customer = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox_Hotel = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jtxt_CardNumber = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtxt_Amount = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtxt_PayDate = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jComboBox_PayType = new javax.swing.JComboBox<>();
        jbtn_Pay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BOOKING DETAILS");

        jLabel3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name:");

        jlbl_Name.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jlbl_Name.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Name.setText("Name Label");

        jLabel5.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Room Type:");

        jlbl_RoomType.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jlbl_RoomType.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_RoomType.setText("Type  Label");

        jLabel7.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Book Date:");

        jlbl_BookDate.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jlbl_BookDate.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_BookDate.setText("Book  Label");

        jLabel9.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Check In Date:");

        jlbl_CheckIn.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jlbl_CheckIn.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_CheckIn.setText("Book  Label");

        jlbl_CheckOut.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jlbl_CheckOut.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_CheckOut.setText("Book  Label");

        jLabel12.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Check Out Date:");

        jLabel13.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nights Stayed:");

        jlbl_Nights.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jlbl_Nights.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Nights.setText("Book  Label");

        jLabel15.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Payment:");

        jlbl_Payment.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_Payment.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Payment.setText("Payment Check");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbl_Name))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jlbl_BookDate))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jlbl_RoomType))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jlbl_CheckOut))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jlbl_CheckIn))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jlbl_Nights))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jlbl_Payment)))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbl_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlbl_RoomType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlbl_BookDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jlbl_CheckIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jlbl_CheckOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jlbl_Nights))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jlbl_Payment))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        jLabel17.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PAYMENT DETAILS");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Customer Name:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 139, -1, -1));

        jtxt_Customer.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Customer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Customer.setEnabled(false);
        jPanel2.add(jtxt_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 133, 199, -1));

        jLabel19.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Hotel Name:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 92, -1, -1));

        jComboBox_Hotel.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jComboBox_Hotel.setEnabled(false);
        jPanel2.add(jComboBox_Hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 83, 160, 38));

        jLabel20.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Card Number:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 183, -1, -1));

        jtxt_CardNumber.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_CardNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jtxt_CardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 177, 166, -1));

        jLabel21.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Amount:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 227, -1, -1));

        jtxt_Amount.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Amount.setEnabled(false);
        jPanel2.add(jtxt_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 221, 120, -1));

        jLabel22.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Payment Date:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 271, -1, -1));

        jtxt_PayDate.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_PayDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_PayDate.setEnabled(false);
        jPanel2.add(jtxt_PayDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 265, 150, -1));

        jLabel23.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Payment Type:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jComboBox_PayType.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jComboBox_PayType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit Card" }));
        jPanel2.add(jComboBox_PayType, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 310, 160, 38));

        jbtn_Pay.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_Pay.setText("Pay Amount");
        jbtn_Pay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_PayActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_Pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Alata", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHECK OUT PAYMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_PayActionPerformed
        try{
            String hotel = jComboBox_Hotel.getSelectedItem().toString();
            String first = booking.getCustomerFirst();
            String last = booking.getCustomerLast();
            int card_num = Integer.parseInt(jtxt_CardNumber.getText());
            double amt = Double.parseDouble(jtxt_Amount.getText());
            Date payDate = new Date();
            String paytype = jComboBox_PayType.getSelectedItem().toString();
            String room_type = jlbl_RoomType.getText();
            int nights = Integer.parseInt(jlbl_Nights.getText());
            
            Payment paymentCheck = new Payment(hotel,first,last,nights,card_num,amt,payDate,paytype);
            paymentCheck.setBookingID(booking.getBookingID());
            paymentCheck.setCustomerID(booking.getCustomerID());
            
            payDAO.addPayment(paymentCheck);
            bookDAO.checkOutRoom(booking);
            homeUI.refreshTable();
            setVisible(false);
            JOptionPane.showMessageDialog(homeUI,"Thank you! Come again!","Transaction Complete",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_PayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeUI_Payment dialog = new HomeUI_Payment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_Hotel;
    private javax.swing.JComboBox<String> jComboBox_PayType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtn_Pay;
    private javax.swing.JLabel jlbl_BookDate;
    private javax.swing.JLabel jlbl_CheckIn;
    private javax.swing.JLabel jlbl_CheckOut;
    private javax.swing.JLabel jlbl_Name;
    private javax.swing.JLabel jlbl_Nights;
    private javax.swing.JLabel jlbl_Payment;
    private javax.swing.JLabel jlbl_RoomType;
    private javax.swing.JTextField jtxt_Amount;
    private javax.swing.JTextField jtxt_CardNumber;
    private javax.swing.JTextField jtxt_Customer;
    private javax.swing.JTextField jtxt_PayDate;
    // End of variables declaration//GEN-END:variables

    private void populateGUI(){
        jlbl_Name.setText(booking.getCustomerFirst() + " " + booking.getCustomerLast());
        jlbl_RoomType.setText(booking.getRoomType());
        jlbl_BookDate.setText(booking.getStrBookDate());
        jlbl_CheckIn.setText(booking.getLSCheckInDate());
        jlbl_CheckOut.setText(booking.getLSCheckOutDate());
        jlbl_Nights.setText(String.format("%d %s",booking.getNumberNights(), (booking.getNumberNights() == 1)? " Night":" Nights"));
        jlbl_Payment.setText(String.valueOf("P"+payment));
        
        try{
            ArrayList<Hotel> list = hotelDAO.getAllHotels();
            
            for(int i = 0;i<list.size();i++){
                jComboBox_Hotel.addItem(list.get(i).getHotelName());
            }
            
            jComboBox_Hotel.setSelectedItem(booking.getHotelName());
            jtxt_Customer.setText(booking.getCustomerFirst() + " " + booking.getCustomerLast());
            jtxt_Amount.setText(jlbl_Payment.getText());
            Date payDate = new Date();
            jtxt_PayDate.setText(payDate.toLocaleString());
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        
    }
}
