/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql.gui;

/**
 *
 * @author Jur Yel
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mysql.core.Hotel;
import mysql.core.Employee;
import mysql.dao.HotelDAO;
import mysql.dao.EmployeeDAO;
public class HomePageUI_AddHotel extends javax.swing.JFrame {

    /**
     * Creates new form HomePageUI_AddHotel
     */
    private EmployeeDAO empDAO;
    private HotelDAO hotelDAO;
    private HomePageUI homeUI;
    public HomePageUI_AddHotel(HomePageUI ui) {
        try{
            empDAO = new EmployeeDAO();
            hotelDAO = new HotelDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(ui);
        homeUI = ui;
    }

    public HomePageUI_AddHotel(){
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_Hotel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_Street = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxt_Barangay = new javax.swing.JTextField();
        jtxt_City = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_ManagerFirst = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_ManagerLast = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxt_ManagerPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxt_ManagerEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxt_ManagerID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jtxt_First1 = new javax.swing.JTextField();
        jtxt_Last1 = new javax.swing.JTextField();
        jtxt_Phone1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jtxt_Email1 = new javax.swing.JTextField();
        jtxt_StaffID1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jtxt_First2 = new javax.swing.JTextField();
        jtxt_Last2 = new javax.swing.JTextField();
        jtxt_Phone2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jtxt_Email2 = new javax.swing.JTextField();
        jtxt_StaffID2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jtxt_First3 = new javax.swing.JTextField();
        jtxt_Last3 = new javax.swing.JTextField();
        jtxt_Phone3 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jtxt_Email3 = new javax.swing.JTextField();
        jtxt_StaffID3 = new javax.swing.JTextField();
        jbtn_Register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Alata", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD HOTEL BRANCH");

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOTEL DETAILS");

        jLabel3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hotel Name:");

        jtxt_Hotel.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Hotel.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Street:");

        jtxt_Street.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Street.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Barangay:");

        jtxt_Barangay.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Barangay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxt_City.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_City.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("City:");

        jLabel7.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Manager - First Name:");

        jtxt_ManagerFirst.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_ManagerFirst.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manager - Last Name:");

        jtxt_ManagerLast.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_ManagerLast.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Number:");

        jtxt_ManagerPhone.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_ManagerPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HOTEL MANAGER");

        jLabel12.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email Address:");

        jtxt_ManagerEmail.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_ManagerEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Manager - Employee ID:");

        jtxt_ManagerID.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_ManagerID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Street, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Barangay, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_City, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_ManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtxt_ManagerFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtxt_ManagerLast, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_ManagerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_ManagerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(322, 322, 322))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(308, 308, 308))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxt_Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxt_Street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxt_Barangay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtxt_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jtxt_ManagerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jtxt_ManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jtxt_ManagerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtxt_ManagerFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxt_ManagerLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HOTEL EMPLOYEES");
        jLabel11.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee #1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Alata", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jtxt_First1.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_First1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_First1.setText("First Name");
        jtxt_First1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_First1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_First1MouseExited(evt);
            }
        });

        jtxt_Last1.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Last1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Last1.setText("Last Name");
        jtxt_Last1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_Last1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_Last1MouseExited(evt);
            }
        });

        jtxt_Phone1.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Phone1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Phone1.setText("Phone Number");
        jtxt_Phone1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_Phone1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_Phone1MouseExited(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Employee", "Hotel Manager" }));
        jComboBox1.setEnabled(false);

        jtxt_Email1.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Email1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Email1.setText("Email Address");
        jtxt_Email1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_Email1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_Email1MouseExited(evt);
            }
        });

        jtxt_StaffID1.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_StaffID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_StaffID1.setText("Employee ID");
        jtxt_StaffID1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_StaffID1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_StaffID1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_Phone1)
                    .addComponent(jtxt_Last1)
                    .addComponent(jtxt_First1)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxt_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_StaffID1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxt_StaffID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jtxt_First1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Last1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee #2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Alata", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jtxt_First2.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_First2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_First2.setText("First Name");
        jtxt_First2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_First2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_First2MouseExited(evt);
            }
        });

        jtxt_Last2.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Last2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Last2.setText("Last Name");
        jtxt_Last2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_Last2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_Last2MouseExited(evt);
            }
        });

        jtxt_Phone2.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Phone2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Phone2.setText("Phone Number");
        jtxt_Phone2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_Phone2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_Phone2MouseExited(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Employee", "Hotel Manager" }));
        jComboBox2.setEnabled(false);

        jtxt_Email2.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Email2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Email2.setText("Email Address");
        jtxt_Email2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_Email2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_Email2MouseExited(evt);
            }
        });

        jtxt_StaffID2.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_StaffID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_StaffID2.setText("Employee ID");
        jtxt_StaffID2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_StaffID2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_StaffID2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_Phone2)
                    .addComponent(jtxt_Last2)
                    .addComponent(jtxt_First2)
                    .addComponent(jComboBox2, 0, 179, Short.MAX_VALUE)
                    .addComponent(jtxt_Email2)
                    .addComponent(jtxt_StaffID2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxt_StaffID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxt_First2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Last2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Email2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee #3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Alata", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jtxt_First3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_First3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_First3.setText("First Name");
        jtxt_First3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_First3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_First3MouseExited(evt);
            }
        });

        jtxt_Last3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Last3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Last3.setText("Last Name");
        jtxt_Last3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_Last3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_Last3MouseExited(evt);
            }
        });

        jtxt_Phone3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Phone3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Phone3.setText("Phone Number");
        jtxt_Phone3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_Phone3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_Phone3MouseExited(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Employee", "Hotel Manager" }));
        jComboBox3.setEnabled(false);

        jtxt_Email3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Email3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Email3.setText("Email Address");
        jtxt_Email3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_Email3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_Email3MouseExited(evt);
            }
        });

        jtxt_StaffID3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_StaffID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_StaffID3.setText("Employee ID");
        jtxt_StaffID3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_StaffID3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_StaffID3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_Phone3)
                    .addComponent(jtxt_Last3)
                    .addComponent(jtxt_First3)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxt_Email3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_StaffID3))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxt_StaffID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxt_First3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Last3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Phone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Email3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jbtn_Register.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_Register.setText("Register Hotel");
        jbtn_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(307, 307, 307))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RegisterActionPerformed
        try{
            String hotel = jtxt_Hotel.getText().trim();
            String street = jtxt_Street.getText().trim();
            String brgy = jtxt_Barangay.getText().trim();
            String city = jtxt_City.getText().trim();
            String mngr_id = jtxt_ManagerID.getText().trim();
            String mngr_first = jtxt_ManagerFirst.getText().trim();
            String mngr_last = jtxt_ManagerLast.getText().trim();
            String phone = jtxt_ManagerPhone.getText().trim();
            String email = jtxt_ManagerEmail.getText().trim();
            
            Hotel newHotel = new Hotel(hotel,null,street,brgy,city,phone);
           
            if(hotelDAO.checkHotelName(hotel)){
                JOptionPane.showMessageDialog(HomePageUI_AddHotel.this,"Hotel already exists!","Register Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                hotelDAO.registerHotel(newHotel);
                int hotelID = hotelDAO.getHotelID(hotel);
                int employees = 0;
                Employee manager = new Employee(mngr_id,hotel,mngr_first,mngr_last,phone,email,"Hotel Manager");
                manager.setHotelID(hotelID);
                empDAO.hireEmployee(manager);
                
                String empID1 = jtxt_StaffID1.getText().trim();
                String first1 = jtxt_First1.getText().trim();
                String last1 = jtxt_Last1.getText().trim();
                String phone1 = jtxt_Phone1.getText().trim();
                String email1 = jtxt_Email1.getText().trim();
                
                String empID2 = jtxt_StaffID2.getText().trim();
                String first2 = jtxt_First2.getText().trim();
                String last2 = jtxt_Last2.getText().trim();
                String phone2 = jtxt_Phone2.getText().trim();
                String email2 = jtxt_Email2.getText().trim();
                
                String empID3 = jtxt_StaffID3.getText().trim();
                String first3 = jtxt_First3.getText().trim();
                String last3 = jtxt_Last3.getText().trim();
                String phone3 = jtxt_Phone3.getText().trim();
                String email3 = jtxt_Email3.getText().trim();
                
                if(!(empID1.equals("Employee ID")) &&
                        !(first1.equals("First Name")) &&
                        !(last1.equals("Last Name")) &&
                        !(phone1.equals("Phone Number")) &&
                        !(email1.equals("Email Address"))){
                    Employee employee1 = new Employee(empID1,hotel,first1,last1,phone1,email1,"Hotel Employee");
                    employee1.setHotelID(hotelID);
                    empDAO.hireEmployee(employee1);
                    employees++;
                }
                if(!(empID2.equals("Employee ID")) &&
                        !(first2.equals("First Name")) &&
                        !(last2.equals("Last Name")) &&
                        !(phone2.equals("Phone Number")) &&
                        !(email2.equals("Email Address"))){
                    Employee employee2 = new Employee(empID2,hotel,first2,last2,phone2,email2,"Hotel Employee");
                    employee2.setHotelID(hotelID);
                    empDAO.hireEmployee(employee2);
                    employees++;
                }
                if(!(empID3.equals("Employee ID")) &&
                        !(first3.equals("First Name")) &&
                        !(last3.equals("Last Name")) &&
                        !(phone3.equals("Phone Number")) &&
                        !(email3.equals("Email Address"))){
                    Employee employee3 = new Employee(empID3,hotel,first3,last3,phone3,email3,"Hotel Employee");
                    employee3.setHotelID(hotelID);
                    empDAO.hireEmployee(employee3);
                    employees++;
                }
                
                newHotel.setEmployees(employees);
                reset();
                HomePageUI_AddRooms addRoomUI = new HomePageUI_AddRooms(hotelID,hotel,newHotel,homeUI);
                setVisible(false);
                addRoomUI.setVisible(true);
            }
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_RegisterActionPerformed

    private void jtxt_StaffID1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_StaffID1MouseEntered
        if(jtxt_StaffID1.getText().contains("Employee ID")){
            jtxt_StaffID1.setText("");
        }
    }//GEN-LAST:event_jtxt_StaffID1MouseEntered

    private void jtxt_StaffID1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_StaffID1MouseExited
        if(jtxt_StaffID1.getText().isEmpty()){
            jtxt_StaffID1.setText("Employee ID");
        }
    }//GEN-LAST:event_jtxt_StaffID1MouseExited

    private void jtxt_First1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_First1MouseEntered
        if(jtxt_First1.getText().contains("First Name")){
            jtxt_First1.setText("");
        }
    }//GEN-LAST:event_jtxt_First1MouseEntered

    private void jtxt_First1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_First1MouseExited
        if(jtxt_First1.getText().isEmpty()){
            jtxt_First1.setText("First Name");
        }
    }//GEN-LAST:event_jtxt_First1MouseExited

    private void jtxt_Last1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Last1MouseEntered
       if(jtxt_Last1.getText().contains("Last Name")){
           jtxt_Last1.setText("");
       }
    }//GEN-LAST:event_jtxt_Last1MouseEntered

    private void jtxt_Last1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Last1MouseExited
        if(jtxt_Last1.getText().isEmpty()){
            jtxt_Last1.setText("Last Name");
        }
    }//GEN-LAST:event_jtxt_Last1MouseExited

    private void jtxt_Phone1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Phone1MouseEntered
        if(jtxt_Phone1.getText().contains("Phone Number")){
            jtxt_Phone1.setText("");
        }
    }//GEN-LAST:event_jtxt_Phone1MouseEntered

    private void jtxt_Phone1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Phone1MouseExited
        if(jtxt_Phone1.getText().isEmpty()){
            jtxt_Phone1.setText("Phone Number");
        }
    }//GEN-LAST:event_jtxt_Phone1MouseExited

    private void jtxt_Email1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Email1MouseEntered
        if(jtxt_Email1.getText().contains("Email Address")){
            jtxt_Email1.setText("");
        }
    }//GEN-LAST:event_jtxt_Email1MouseEntered

    private void jtxt_Email1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Email1MouseExited
        if(jtxt_Email1.getText().isEmpty()){
            jtxt_Email1.setText("Email Address");
        }
    }//GEN-LAST:event_jtxt_Email1MouseExited

    private void jtxt_StaffID2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_StaffID2MouseEntered
        if(jtxt_StaffID2.getText().contains("Employee ID")){
            jtxt_StaffID2.setText("");
        }
    }//GEN-LAST:event_jtxt_StaffID2MouseEntered

    private void jtxt_StaffID2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_StaffID2MouseExited
        if(jtxt_StaffID2.getText().isEmpty()){
            jtxt_StaffID2.setText("Employee ID");
        }
    }//GEN-LAST:event_jtxt_StaffID2MouseExited

    private void jtxt_First2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_First2MouseEntered
        if(jtxt_First2.getText().contains("First Name")){
            jtxt_First2.setText("");
        }
    }//GEN-LAST:event_jtxt_First2MouseEntered

    private void jtxt_First2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_First2MouseExited
        if(jtxt_First2.getText().isEmpty()){
            jtxt_First2.setText("First Name");
        }
    }//GEN-LAST:event_jtxt_First2MouseExited

    private void jtxt_Last2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Last2MouseEntered
        if(jtxt_Last2.getText().contains("Last Name")){
            jtxt_Last2.setText("");
        }
    }//GEN-LAST:event_jtxt_Last2MouseEntered

    private void jtxt_Last2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Last2MouseExited
        if(jtxt_Last2.getText().isEmpty()){
            jtxt_Last2.setText("Last Name");
        }
    }//GEN-LAST:event_jtxt_Last2MouseExited

    private void jtxt_Phone2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Phone2MouseEntered
        if(jtxt_Phone2.getText().contains("Phone Number")){
            jtxt_Phone2.setText("");
        }
    }//GEN-LAST:event_jtxt_Phone2MouseEntered

    private void jtxt_Phone2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Phone2MouseExited
       if(jtxt_Phone2.getText().isEmpty()){
           jtxt_Phone2.setText("Phone Number");
       }
    }//GEN-LAST:event_jtxt_Phone2MouseExited

    private void jtxt_Email2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Email2MouseEntered
        if(jtxt_Email2.getText().contains("Email Address")){
            jtxt_Email2.setText("");
        }
    }//GEN-LAST:event_jtxt_Email2MouseEntered

    private void jtxt_Email2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Email2MouseExited
        if(jtxt_Email2.getText().isEmpty()){
            jtxt_Email2.setText("Email Address");
        }
    }//GEN-LAST:event_jtxt_Email2MouseExited

    private void jtxt_StaffID3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_StaffID3MouseEntered
        if(jtxt_StaffID3.getText().contains("Employee ID")){
            jtxt_StaffID3.setText("");
        }
    }//GEN-LAST:event_jtxt_StaffID3MouseEntered

    private void jtxt_StaffID3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_StaffID3MouseExited
        if(jtxt_StaffID3.getText().isEmpty()){
            jtxt_StaffID3.setText("Employee ID");
        }
    }//GEN-LAST:event_jtxt_StaffID3MouseExited

    private void jtxt_First3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_First3MouseEntered
        if(jtxt_First3.getText().contains("First Name")){
            jtxt_First3.setText("");
        }
    }//GEN-LAST:event_jtxt_First3MouseEntered

    private void jtxt_First3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_First3MouseExited
        if(jtxt_First3.getText().isEmpty()){
            jtxt_First3.setText("First Name");
        }
    }//GEN-LAST:event_jtxt_First3MouseExited

    private void jtxt_Last3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Last3MouseEntered
        if(jtxt_Last3.getText().contains("Last Name")){
            jtxt_Last3.setText("");
        }
    }//GEN-LAST:event_jtxt_Last3MouseEntered

    private void jtxt_Last3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Last3MouseExited
        if(jtxt_Last3.getText().isEmpty()){
            jtxt_Last3.setText("Last Name");
        }
    }//GEN-LAST:event_jtxt_Last3MouseExited

    private void jtxt_Phone3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Phone3MouseEntered
        if(jtxt_Phone3.getText().contains("Phone Number")){
            jtxt_Phone3.setText("");
        }
    }//GEN-LAST:event_jtxt_Phone3MouseEntered

    private void jtxt_Phone3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Phone3MouseExited
        if(jtxt_Phone3.getText().isEmpty()){
            jtxt_Phone3.setText("Phone Number");
        }
    }//GEN-LAST:event_jtxt_Phone3MouseExited

    private void jtxt_Email3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Email3MouseEntered
        if(jtxt_Email3.getText().contains("Email Address")){
            jtxt_Email3.setText("");
        }
    }//GEN-LAST:event_jtxt_Email3MouseEntered

    private void jtxt_Email3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_Email3MouseExited
        if(jtxt_Email3.getText().isEmpty()){
            jtxt_Email3.setText("Email Address");
        }
    }//GEN-LAST:event_jtxt_Email3MouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        homeUI.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageUI_AddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageUI_AddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageUI_AddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageUI_AddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageUI_AddHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbtn_Register;
    private javax.swing.JTextField jtxt_Barangay;
    private javax.swing.JTextField jtxt_City;
    private javax.swing.JTextField jtxt_Email1;
    private javax.swing.JTextField jtxt_Email2;
    private javax.swing.JTextField jtxt_Email3;
    private javax.swing.JTextField jtxt_First1;
    private javax.swing.JTextField jtxt_First2;
    private javax.swing.JTextField jtxt_First3;
    private javax.swing.JTextField jtxt_Hotel;
    private javax.swing.JTextField jtxt_Last1;
    private javax.swing.JTextField jtxt_Last2;
    private javax.swing.JTextField jtxt_Last3;
    private javax.swing.JTextField jtxt_ManagerEmail;
    private javax.swing.JTextField jtxt_ManagerFirst;
    private javax.swing.JTextField jtxt_ManagerID;
    private javax.swing.JTextField jtxt_ManagerLast;
    private javax.swing.JTextField jtxt_ManagerPhone;
    private javax.swing.JTextField jtxt_Phone1;
    private javax.swing.JTextField jtxt_Phone2;
    private javax.swing.JTextField jtxt_Phone3;
    private javax.swing.JTextField jtxt_StaffID1;
    private javax.swing.JTextField jtxt_StaffID2;
    private javax.swing.JTextField jtxt_StaffID3;
    private javax.swing.JTextField jtxt_Street;
    // End of variables declaration//GEN-END:variables

    private void reset(){
        jtxt_Hotel.setText("");
        jtxt_Street.setText("");
        jtxt_Barangay.setText("");
        jtxt_City.setText("");
        
        jtxt_ManagerID.setText("");
        jtxt_ManagerFirst.setText("");
        jtxt_ManagerLast.setText("");
        jtxt_ManagerPhone.setText("");
        jtxt_ManagerEmail.setText("");
        
        jtxt_StaffID1.setText("Employee ID");
        jtxt_First1.setText("First Name");
        jtxt_Last1.setText("Last Name");
        jtxt_Phone1.setText("Phone Number");
        jtxt_Email1.setText("Email Address");
        
        jtxt_StaffID2.setText("Employee ID");
        jtxt_First2.setText("First Name");
        jtxt_Last2.setText("Last Name");
        jtxt_Phone2.setText("Phone Number");
        jtxt_Email2.setText("Email Address");
        
        jtxt_StaffID3.setText("Employee ID");
        jtxt_First3.setText("First Name");
        jtxt_Last3.setText("Last Name");
        jtxt_Phone3.setText("Phone Number");
        jtxt_Email3.setText("Email Address");
    }
}
