/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql.gui;

/**
 *
 * @author Jur Yel
 */
import java.util.ArrayList;
import mysql.core.Booking;
import mysql.dao.BookingDAO;
import java.util.Date;
import javax.swing.JOptionPane;
import mysql.dao.CustomerDAO;
import java.sql.Timestamp;
import javax.swing.JPanel;
import mysql.dao.HotelDAO;
import mysql.dao.CustomerRecordsDAO;

public class HomePageUI extends javax.swing.JFrame {

    /**
     * Creates new form HomePageUI
     */
    private BookingDAO bookDAO;
    private CustomerDAO custDAO;
    private HotelDAO hotelDAO;
    private CustomerRecordsDAO recordDAO;
    private String hotel_name;
    
    public HomePageUI(String hotel) {
        try{
            bookDAO = new BookingDAO();
            custDAO = new CustomerDAO();
            recordDAO = new CustomerRecordsDAO();
            hotelDAO = new HotelDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        hotel_name = hotel;
        populateTable();
        passTime();
        
        
    }

    public HomePageUI(){
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_Search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Bookings = new javax.swing.JTable();
        jbtn_Refresh = new javax.swing.JButton();
        jbtn_CheckOut = new javax.swing.JButton();
        jbtn_Cancel = new javax.swing.JButton();
        jbtn_CheckIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Alata", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SIDEBAR");

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Alata", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HOME");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Alata", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("REGISTER NEW HOTEL");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Alata", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BOOK ROOM");
        jLabel6.setToolTipText("");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Alata", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HOTEL RECORDS");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Alata", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADD NEW ROOMS");
        jLabel8.setToolTipText("");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(82, 82, 82))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 694));

        jLabel2.setFont(new java.awt.Font("Alata", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOTEL BOOKINGS");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jtxt_Search.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Search.setText("Search Booking");
        jtxt_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_SearchMouseExited(evt);
            }
        });
        jtxt_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_SearchKeyTyped(evt);
            }
        });
        jPanel3.add(jtxt_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 69, 237, 40));

        jtbl_Bookings.setFont(new java.awt.Font("Alata", 0, 12)); // NOI18N
        jtbl_Bookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_Bookings);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 129, 904, 497));

        jbtn_Refresh.setFont(new java.awt.Font("Alata", 0, 12)); // NOI18N
        jbtn_Refresh.setText("Record Data");
        jbtn_Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RefreshActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn_Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 100, -1, -1));

        jbtn_CheckOut.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_CheckOut.setText("Check Out");
        jbtn_CheckOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CheckOutActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn_CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 640, 130, 40));

        jbtn_Cancel.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_Cancel.setText("Cancel Booking");
        jbtn_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CancelActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 130, 40));

        jbtn_CheckIn.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_CheckIn.setText("Check In");
        jbtn_CheckIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CheckInActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn_CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 130, 40));

        jLabel1.setFont(new java.awt.Font("Alata", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOTEL MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_SearchMouseEntered
        if(jtxt_Search.getText().contains("Search Booking")){
            jtxt_Search.setText("");
        }
    }//GEN-LAST:event_jtxt_SearchMouseEntered

    private void jtxt_SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_SearchMouseExited
       if(jtxt_Search.getText().isEmpty()){
           jtxt_Search.setText("Search Booking");
       }
    }//GEN-LAST:event_jtxt_SearchMouseExited

    private void jtxt_SearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_SearchKeyTyped
        String search = jtxt_Search.getText().trim();
        try{
            int id = hotelDAO.getHotelID(hotel_name);
            if(search.isEmpty()){
                ArrayList<Booking> list = bookDAO.getHotelBookings(id);
                BookingTableModel model = new BookingTableModel(list);
                jtbl_Bookings.setModel(model);
            }
            else{
                ArrayList<Booking> list = bookDAO.searchHotelBooking(id,search);
                BookingTableModel model = new BookingTableModel(list);
                jtbl_Bookings.setModel(model);
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jtxt_SearchKeyTyped

    private void jbtn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CancelActionPerformed
        int row = jtbl_Bookings.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(HomePageUI.this,"Select a row","Cancel Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                Booking book = (Booking)jtbl_Bookings.getValueAt(row,BookingTableModel.OBJECT_COL);
                Date book_date = book.getBookDate();

                /* Alternative class fetching */
                ArrayList<Booking> list = bookDAO.getAllBookings();
                Booking theBook = list.get(row);
                /* END */

                int bookID = Integer.parseInt(jtbl_Bookings.getValueAt(row,-2).toString());
                if(!(bookDAO.checkIfBookingCheckedIn(bookID))){
                    if((JOptionPane.showConfirmDialog(HomePageUI.this,"Cancel booking?","Confirm Cancel",
                            JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)) == JOptionPane.YES_OPTION){
                        bookDAO.cancelBooking(bookID);
                        populateTable();
                        JOptionPane.showMessageDialog(HomePageUI.this,"Booking has been cancelled!","Cancelled Booking",JOptionPane.INFORMATION_MESSAGE);

                    }
                }
                
            }
            catch(Exception exc){
                exc.printStackTrace();
            } 
        }
       
    }//GEN-LAST:event_jbtn_CancelActionPerformed

    private void jbtn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RefreshActionPerformed
        try{
            int id = hotelDAO.getHotelID(hotel_name);
            bookDAO.recordData(id);
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_RefreshActionPerformed

    private void jbtn_CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CheckInActionPerformed
        int row = jtbl_Bookings.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(HomePageUI.this,"Select a row","Check In Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                
                
                int bookID = Integer.parseInt(jtbl_Bookings.getValueAt(row,-2).toString());
                    String hotel = jtbl_Bookings.getValueAt(row,0).toString();
                    String first = jtbl_Bookings.getValueAt(row,1).toString();
                    String last = jtbl_Bookings.getValueAt(row,2).toString();
                    String type = jtbl_Bookings.getValueAt(row,3).toString();
                    String book_date = jtbl_Bookings.getValueAt(row,4).toString();
                    int roomID = bookDAO.getRoomID(bookID);
                    int hotel_id = hotelDAO.getHotelID(hotel);
                    int custID = custDAO.getCustomerID(first + " " + last);
                    
                    Booking book = new Booking(null,first,last,type,null,null,null,0);
                    book.setStrBookDate(book_date);
                    book.setBookingID(bookID);
                    book.setCustomerID(custID);
                    book.setHotelID(hotel_id);
                    book.setRoomID(roomID);
                
                if(bookDAO.checkIfBooked(bookID)){
                    bookDAO.checkInBookedRoom(book);
                    JOptionPane.showMessageDialog(HomePageUI.this,
                            "Customer has now checked in; \n\n"
                          + "Customer: " + String.format("%s %s",first,last) + "\n"
                          + "Room Type: " + book.getRoomType() + "\n"
                          + "Date Booked: " + book.getLSBookDate() + "\n"
                          + "Checked In: " + (new Timestamp(System.currentTimeMillis())).toLocaleString() + "\n\n"
                          + "Enjoy your stay!","Checked In",JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    bookDAO.checkInRoom(book);
                    JOptionPane.showMessageDialog(HomePageUI.this,
                            "Customer has now checked in; \n\n"
                          + "Customer: " + String.format("%s %s",first,last) + "\n"
                          + "Room Type: " + book.getRoomType() + "\n"
                          + "Date Booked: " + book.getLSBookDate() + "\n"
                          + "Checked In: " + (new Timestamp(System.currentTimeMillis())).toLocaleString() + "\n\n"
                          + "Enjoy your stay!","Checked In",JOptionPane.INFORMATION_MESSAGE);
                }
                populateTable();
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbtn_CheckInActionPerformed

    private void jbtn_CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CheckOutActionPerformed
        int row = jtbl_Bookings.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(HomePageUI.this,"Select a row","Check Out Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                String checkin = jtbl_Bookings.getValueAt(row,5).toString();
                
                if(checkin.equals(" ")){
                    JOptionPane.showMessageDialog(HomePageUI.this,"Check in and spend a night first","Check Out Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    Date checkout = new Date();
                    
                    int bookID = Integer.parseInt(jtbl_Bookings.getValueAt(row,-2).toString());
                    String hotel = jtbl_Bookings.getValueAt(row,0).toString();
                    String first = jtbl_Bookings.getValueAt(row,1).toString();
                    String last = jtbl_Bookings.getValueAt(row,2).toString();
                    String type = jtbl_Bookings.getValueAt(row,3).toString();
                    String book_date = jtbl_Bookings.getValueAt(row,4).toString();
                    int roomID = bookDAO.getRoomID(bookID);
                    int hotel_id = hotelDAO.getHotelID(hotel);
                    int customerID = custDAO.getCustomerID(first + " " + last);
                    Date inDate = bookDAO.getCheckInDate(bookID);
                    int inDay = inDate.getDate();
                    int outDay = checkout.getDate();
                    int nights = (outDay - inDay);
                    
                    if(nights > 0){
                        Booking book = new Booking(null,first,last,type,null,inDate,checkout,nights);
                        book.setStrBookDate(book_date);
                        book.setBookingID(bookID);
                        book.setCustomerID(customerID);
                        book.setHotelID(hotel_id);
                        book.setRoomID(roomID);

                        double payment = bookDAO.calculateRate(book);

                        HomeUI_Payment payUI = new HomeUI_Payment(book,bookDAO,payment,HomePageUI.this);
                        payUI.setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(HomePageUI.this,"Spend a night first","Check Out Error",JOptionPane.ERROR_MESSAGE);
                    }
                    
                }
                
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbtn_CheckOutActionPerformed

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
       panelColor(jPanel5);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        resetPanelColor(jPanel5);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        panelColor(jPanel5);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
       resetPanelColor(jPanel5);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        panelColor(jPanel8);
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        resetPanelColor(jPanel8);
    }//GEN-LAST:event_jPanel8MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        panelColor(jPanel8);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        resetPanelColor(jPanel8);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        panelColor(jPanel6);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        resetPanelColor(jPanel6);
    }//GEN-LAST:event_jPanel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        panelColor(jPanel6);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        resetPanelColor(jPanel6);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        panelColor(jPanel7);
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        resetPanelColor(jPanel7);
    }//GEN-LAST:event_jPanel7MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        panelColor(jPanel7);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        resetPanelColor(jPanel7);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        HomePageUI_AddHotel addHotelUI = new HomePageUI_AddHotel(HomePageUI.this);
        setVisible(false);
        addHotelUI.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        HomePageUI_AddHotel addHotelUI = new HomePageUI_AddHotel(HomePageUI.this);
        setVisible(false);
        addHotelUI.setVisible(true);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       HomePageUI_MainAddRooms addRoomUI = new HomePageUI_MainAddRooms(HomePageUI.this);
       setVisible(false);
       addRoomUI.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        HomePageUI_AddHotel addHotelUI = new HomePageUI_AddHotel(HomePageUI.this);
        setVisible(false);
        addHotelUI.setVisible(true);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try{
            int hotelID = hotelDAO.getHotelID(hotel_name);
            HomePageUI_BookRoom bookUI = new HomePageUI_BookRoom(hotelID,hotel_name,HomePageUI.this);
            setVisible(false);
            bookUI.setVisible(true);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        try{
            int hotelID = hotelDAO.getHotelID(hotel_name);
            HomePageUI_BookRoom bookUI = new HomePageUI_BookRoom(hotelID,hotel_name,HomePageUI.this);
            setVisible(false);
            bookUI.setVisible(true);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        try{
            int id = hotelDAO.getHotelID(hotel_name);
            HomePageUI_RecordsMenu menuUI = new HomePageUI_RecordsMenu(id,hotel_name,HomePageUI.this);
            menuUI.setVisible(true);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try{
            int id = hotelDAO.getHotelID(hotel_name);
            HomePageUI_RecordsMenu menuUI = new HomePageUI_RecordsMenu(id,hotel_name,HomePageUI.this);
            menuUI.setVisible(true);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_Cancel;
    private javax.swing.JButton jbtn_CheckIn;
    private javax.swing.JButton jbtn_CheckOut;
    private javax.swing.JButton jbtn_Refresh;
    private javax.swing.JTable jtbl_Bookings;
    private javax.swing.JTextField jtxt_Search;
    // End of variables declaration//GEN-END:variables
    
    public void refreshTable(){
        try{
             int id = hotelDAO.getHotelID(hotel_name);
            ArrayList<Booking> list = bookDAO.getHotelBookings(id);
            BookingTableModel model = new BookingTableModel(list);
            jtbl_Bookings.setModel(model);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    private void populateTable(){
        try{
            int id = hotelDAO.getHotelID(hotel_name);
            ArrayList<Booking> list = bookDAO.getHotelBookings(id);
            BookingTableModel model = new BookingTableModel(list);
            jtbl_Bookings.setModel(model);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    private void passTime(){
        try{
            int id = hotelDAO.getHotelID(hotel_name);
            bookDAO.passTime(id);
            populateTable();
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    private void panelColor(JPanel panel){
        panel.setBackground(new java.awt.Color(0,204,204));
    }
    
    private void resetPanelColor(JPanel panel){
        panel.setBackground(new java.awt.Color(0,153,153));
    }
}
