/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql.gui;

/**
 *
 * @author Jur Yel
 */
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mysql.core.Hotel;
import mysql.dao.HotelDAO;
import mysql.core.Employee;
import mysql.dao.EmployeeDAO;
public class StartUI_Register extends javax.swing.JFrame {

    /**
     * Creates new form StartUI_Register
     */
    private EmployeeDAO empDAO;
    private HotelDAO hotelDAO;
    public StartUI_Register() {
        try{
            empDAO = new EmployeeDAO();
            hotelDAO = new HotelDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        populateGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Branch = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jtxt_EmployeeID = new javax.swing.JTextField();
        jtxt_First = new javax.swing.JTextField();
        jtxt_Email = new javax.swing.JTextField();
        jtxt_Last = new javax.swing.JTextField();
        jtxt_Phone = new javax.swing.JTextField();
        jpf_Password = new javax.swing.JPasswordField();
        jCheckBox_Show = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jbtn_Register = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Alata", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SYSTEM");

        jLabel2.setFont(new java.awt.Font("Alata", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGEMENT");

        jLabel1.setFont(new java.awt.Font("Alata", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOTEL");

        jComboBox_Branch.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jComboBox_Branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Branch" }));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxt_EmployeeID.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_EmployeeID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_EmployeeID.setText("Employee ID");
        jtxt_EmployeeID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_EmployeeIDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_EmployeeIDMouseExited(evt);
            }
        });
        jtxt_EmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_EmployeeIDActionPerformed(evt);
            }
        });

        jtxt_First.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_First.setText("First Name");
        jtxt_First.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_FirstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_FirstMouseExited(evt);
            }
        });

        jtxt_Email.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Email.setText("Email Address");
        jtxt_Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_EmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_EmailMouseExited(evt);
            }
        });

        jtxt_Last.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Last.setText("Last Name");
        jtxt_Last.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_LastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_LastMouseExited(evt);
            }
        });

        jtxt_Phone.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Phone.setText("Phone Number");
        jtxt_Phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_PhoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_PhoneMouseExited(evt);
            }
        });

        jpf_Password.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jpf_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpf_Password.setText("Password");
        jpf_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpf_PasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpf_PasswordMouseExited(evt);
            }
        });
        jpf_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpf_PasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpf_PasswordKeyTyped(evt);
            }
        });

        jCheckBox_Show.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jCheckBox_Show.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_Show.setText("Show Password");
        jCheckBox_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_EmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jtxt_First))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_Last, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jpf_Password))
                        .addGap(98, 98, 98))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox_Show)
                .addGap(128, 128, 128))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jCheckBox_Show))
        );

        jLabel4.setFont(new java.awt.Font("Alata", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTER");

        jbtn_Register.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_Register.setText("Register");
        jbtn_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RegisterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("Login Account");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jComboBox_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addGap(85, 85, 85))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)))
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jComboBox_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_Register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_EmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_EmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_EmployeeIDActionPerformed

    private void jCheckBox_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ShowActionPerformed
        if(jCheckBox_Show.isSelected()){
            jpf_Password.setEchoChar((char)0);
        }
        else{
            jpf_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_ShowActionPerformed

    private void jtxt_EmployeeIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmployeeIDMouseEntered
        if(jtxt_EmployeeID.getText().contains("Employee ID")){
            jtxt_EmployeeID.setText("");
        }
    }//GEN-LAST:event_jtxt_EmployeeIDMouseEntered

    private void jtxt_EmployeeIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmployeeIDMouseExited
       if(jtxt_EmployeeID.getText().isEmpty()){
           jtxt_EmployeeID.setText("Employee ID");
       }
    }//GEN-LAST:event_jtxt_EmployeeIDMouseExited

    private void jtxt_EmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmailMouseEntered
        if(jtxt_Email.getText().contains("Email Address")){
            jtxt_Email.setText("");
        }
    }//GEN-LAST:event_jtxt_EmailMouseEntered

    private void jtxt_EmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmailMouseExited
       if(jtxt_Email.getText().isEmpty()){
           jtxt_Email.setText("Email Address");
       }
    }//GEN-LAST:event_jtxt_EmailMouseExited

    private void jtxt_FirstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_FirstMouseEntered
        if(jtxt_First.getText().contains("First Name")){
            jtxt_First.setText("");
        }
    }//GEN-LAST:event_jtxt_FirstMouseEntered

    private void jtxt_FirstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_FirstMouseExited
        if(jtxt_First.getText().isEmpty()){
            jtxt_First.setText("First Name");
        }
    }//GEN-LAST:event_jtxt_FirstMouseExited

    private void jtxt_LastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_LastMouseEntered
       if(jtxt_Last.getText().contains("Last Name")){
           jtxt_Last.setText("");
       }
    }//GEN-LAST:event_jtxt_LastMouseEntered

    private void jtxt_LastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_LastMouseExited
        if(jtxt_Last.getText().isEmpty()){
            jtxt_Last.setText("Last Name");
        }
    }//GEN-LAST:event_jtxt_LastMouseExited

    private void jtxt_PhoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_PhoneMouseEntered
        if(jtxt_Phone.getText().contains("Phone Number")){
            jtxt_Phone.setText("");
        }
    }//GEN-LAST:event_jtxt_PhoneMouseEntered

    private void jtxt_PhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_PhoneMouseExited
       if(jtxt_Phone.getText().isEmpty()){
           jtxt_Phone.setText("Phone Number");
       }
    }//GEN-LAST:event_jtxt_PhoneMouseExited

    private void jpf_PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpf_PasswordMouseEntered
        if(jpf_Password.getText().contains("Password")){
            jpf_Password.setText("");
        }
    }//GEN-LAST:event_jpf_PasswordMouseEntered

    private void jpf_PasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpf_PasswordMouseExited
        if(jpf_Password.getText().isEmpty()){
            jpf_Password.setEchoChar((char)0);
            jpf_Password.setText("Password");
        }
    }//GEN-LAST:event_jpf_PasswordMouseExited

    private void jpf_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_PasswordKeyTyped
        jpf_Password.setEchoChar('*');
    }//GEN-LAST:event_jpf_PasswordKeyTyped

    private void jbtn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RegisterActionPerformed
        try{
            String id = jtxt_EmployeeID.getText().trim();
            String email = jtxt_Email.getText().trim();
            String first = jtxt_First.getText().trim();
            String last = jtxt_Last.getText().trim();
            String phone = jtxt_Phone.getText().trim();
            String pass = jpf_Password.getText().trim();
            String hotel = jComboBox_Branch.getSelectedItem().toString();
            int hotelID = hotelDAO.getHotelID(hotel);
            if(hotel.equals("Hotel Branch")){
                JOptionPane.showMessageDialog(StartUI_Register.this,"Select a hotel branch","Register Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                if((id.equals("Employee ID")) ||
                        (email.equals("Email Address"))||
                        (first.equals("First Name")) ||
                        (last.equals("Last Name"))||
                        (phone.equals("Phone Number"))||
                        (pass.equals("Password"))){
                    JOptionPane.showMessageDialog(StartUI_Register.this,"Fill up all fields","Register Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(empDAO.checkEmployeeID(id)){
                        JOptionPane.showMessageDialog(StartUI_Register.this,"Employee ID already exists!","Register Error",JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        Employee employee = new Employee(id,hotel,first,last,phone,email,"Hotel Employee");
                        employee.setPassword(pass);
                        employee.setHotelID(hotelID);
                        
                        empDAO.registerEmployee(employee);
                        
                        JOptionPane.showMessageDialog(StartUI_Register.this,"Employee registered successfully!","Register Success",JOptionPane.INFORMATION_MESSAGE);
                        setVisible(false);
                        StartUI_Login loginUI = new StartUI_Login();
                        loginUI.setVisible(true);
                    }
                }
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_RegisterActionPerformed

    private void jpf_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_PasswordKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
             String id = jtxt_EmployeeID.getText().trim();
             String email = jtxt_Email.getText().trim();
             String first = jtxt_First.getText().trim();
             String last = jtxt_Last.getText().trim();
             String phone = jtxt_Phone.getText().trim();
             String pass = jpf_Password.getText().trim();
             String hotel = jComboBox_Branch.getSelectedItem().toString();

             if(hotel.equals("Hotel Branch")){
                 JOptionPane.showMessageDialog(StartUI_Register.this,"Select a hotel branch","Register Error",JOptionPane.ERROR_MESSAGE);
             }
             else{
                 if((id.equals("Employee ID")) ||
                         (email.equals("Email Address"))||
                         (first.equals("First Name")) ||
                         (last.equals("Last Name"))||
                         (phone.equals("Phone Number"))||
                         (pass.equals("Password"))){
                     JOptionPane.showMessageDialog(StartUI_Register.this,"Fill up all fields","Register Error",JOptionPane.ERROR_MESSAGE);
                 }
                 else{
                     if(empDAO.checkEmployeeID(id)){
                         JOptionPane.showMessageDialog(StartUI_Register.this,"Employee ID already exists!","Register Error",JOptionPane.ERROR_MESSAGE);
                     }
                     else{
                         Employee employee = new Employee(id,hotel,first,last,phone,email,"Hotel Employee");
                         employee.setPassword(pass);

                         empDAO.registerEmployee(employee);

                         JOptionPane.showMessageDialog(StartUI_Register.this,"Employee registered successfully!","Register Success",JOptionPane.INFORMATION_MESSAGE);
                         setVisible(false);
                         StartUI_Login loginUI = new StartUI_Login();
                         loginUI.setVisible(true);
                     }
                 }
             }
         }
         catch(Exception exc){
             exc.printStackTrace();
         }
       }
    }//GEN-LAST:event_jpf_PasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUI_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_Show;
    private javax.swing.JComboBox<String> jComboBox_Branch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_Register;
    private javax.swing.JPasswordField jpf_Password;
    private javax.swing.JTextField jtxt_Email;
    private javax.swing.JTextField jtxt_EmployeeID;
    private javax.swing.JTextField jtxt_First;
    private javax.swing.JTextField jtxt_Last;
    private javax.swing.JTextField jtxt_Phone;
    // End of variables declaration//GEN-END:variables

    private void populateGUI(){
        try{
            ArrayList<Hotel> list = hotelDAO.getAllHotels();
            for(int i = 0; i<list.size();i++){
                jComboBox_Branch.addItem(list.get(i).getHotelName());
            }
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
}

